language: python

# needed to use trusty
sudo: required

dist: trusty

branches:
  only:
    - master

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codecov
  - pip install flit
  - flit build
  - flit install

script:
  - coverage run --source=twstock -m unittest

after_success:
  - coveralls
  - codecov
