package main

import (
	"fmt"
)

func main() {
	fmt.Println("Frequent words problem ...")

	txt1 := "ACGTTGCATGTCGCATGATGCATGAGAGCT"
	k1 := 4
	// CATG GCAT

	txt2 := "TGGTAGCGACGTTGGTCCCGCCGCTTGAGAATCTGGATGAACATAAGCTCCCACTTGGCTTATTCAGAGAACTGGTCAACACTTGTCTCTCCCAGCCAGGTCTGACCACCGGGCAACTTTTAGAGCACTATCGTGGTACAAATAATGCTGCCAC"
	k2 := 3
	// TGG

	txt3 := "CAGTGGCAGATGACATTTTGCTGGTCGACTGGTTACAACAACGCCTGGGGCTTTTGAGCAACGAGACTTTTCAATGTTGCACCGTTTGCTGCATGATATTGAAAACAATATCACCAAATAAATAACGCCTTAGTAAGTAGCTTTT"
	k3 := 4
	// TTTT

	txt4 := "ATACAATTACAGTCTGGAACCGGATGAACTGGCCGCAGGTTAACAACAGAGTTGCCAGGCACTGCCGCTGACCAGCAACAACAACAATGACTTTGACGCGAAGGGGATGGCATGAGCGAACTGATCGTCAGCCGTCAGCAACGAGTATTGTTGCTGACCCTTAACAATCCCGCCGCACGTAATGCGCTAACTAATGCCCTGCTG"
	k4 := 5
	// AACAA

	txt5 := "CCAGCGGGGGTTGATGCTCTGGGGGTCACAAGATTGCATTTTTATGGGGTTGCAAAAATGTTTTTTACGGCAGATTCATTTAAAATGCCCACTGGCTGGAGACATAGCCCGGATGCGCGTCTTTTACAACGTATTGCGGGGTAAAATCGTAGATGTTTTAAAATAGGCGTAAC"
	k5 := 5
	// AAAAT GGGGT TTTTA

	txt6 := "CATATAAGTAGAACTAATCTTGCTTAACTTGCTTAACGTTCCCCCCTCCGCTTTGAACTAATCCATATAAGTAGAACTAATCGAACTAATCCTCCGCTTTGAACTAATCTTGCTTAACGAACTAATCGAACTAATCTTGCTTAACTTGCTTAACTTGCTTAACGTTCCCCCGTTCCCCCGAACTAATCCATATAAGTACTCCGCTTTCTCCGCTTTGAACTAATCGTTCCCCCGAACTAATCCATATAAGTACATATAAGTAGTTCCCCCGAACTAATCGAACTAATCCTCCGCTTTCATATAAGTAGAACTAATCTTGCTTAACCATATAAGTACATATAAGTATTGCTTAACTTGCTTAACGAACTAATCTTGCTTAACGAACTAATCGTTCCCCCTTGCTTAACGAACTAATCTTGCTTAACTTGCTTAACTTGCTTAACCATATAAGTAGAACTAATCGTTCCCCCGTTCCCCCGAACTAATCGTTCCCCCCTCCGCTTTCTCCGCTTTCTCCGCTTTCTCCGCTTTGAACTAATCGTTCCCCCGTTCCCCCTTGCTTAACGTTCCCCCCTCCGCTTTCATATAAGTACTCCGCTTTGTTCCCCCCTCCGCTTTCTCCGCTTTTTGCTTAACGTTCCCCCGAACTAATCCATATAAGTACTCCGCTTTTTGCTTAACGTTCCCCCTTGCTTAACTTGCTTAACCATATAAGTAGAACTAATCCTCCGCTTTGAACTAATCCTCCGCTTTTTGCTTAACCTCCGCTTTCATATAAGTACTCCGCTTTGAACTAATCGAACTAATCCATATAAGTACATATAAGTAGAACTAATCGTTCCCCCGTTCCCCCGTTCCCCCGAACTAATCGTTCCCCCGTTCCCCCCATATAAGTACATATAAGTAGTTCCCCCTTGCTTAACTTGCTTAAC"
	k6 := 11
	// CCATATAAGTA

	fmt.Println(" Frequent words [CATG GCAT]:", FrequentWords(txt1, k1))
	fmt.Println(" Frequent words [TGG]:", FrequentWords(txt2, k2))
	fmt.Println(" Frequent words [TTTT]:", FrequentWords(txt3, k3))
	fmt.Println(" Frequent words [AACAA]:", FrequentWords(txt4, k4))
	fmt.Println(" Frequent words [AAAAT GGGGT TTTTA]:", FrequentWords(txt5, k5))
	fmt.Println(" Frequent words [CCATATAAGTA]:", FrequentWords(txt6, k6))
}

func FrequentWords(text string, k int) []string {
	freqWords := make([]string, 0)
	freqMap := FrequencyMap(text, k)
	maxVal := MaxDict(freqMap)

	for key, val := range freqMap {
		if val == maxVal {
			freqWords = append(freqWords, key)
		}
	}
	return freqWords
}

/*
 FrequencyMap()
	Input: a string text and an integer k
	Output: a map w/ string keys and integer values
*/
func FrequencyMap(text string, k int) map[string]int {
	freqMap := make(map[string]int)

	for i := 0; i < len(text)-k+1; i++ {
		freqMap[text[i:i+k]]++
	}

	return freqMap
}

// MaxDict()
//	Input: a dictionary w/ string key and integer value
// 	Output: the maximum value of the values in dictionary
func MaxDict(dict map[string]int) int {
	max := 0
	firstIter := true
	for _, val := range dict {
		if firstIter == true {
			max = val
			firstIter = false
		}
		if val > max {
			max = val
		}
	}
	return max
}
